markdown: redcarpet
baseurl: 
exclude: ['README.md', 'LICENSE', '_old']

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project_page
      extra_css: project_page.css

plugins:
  - jekyll-seo-tag